/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fretron.Model;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DeviceConnectionState extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1302864950078912507L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeviceConnectionState\",\"namespace\":\"com.fretron.Model\",\"fields\":[{\"name\":\"imei\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lastBatteryValue\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"lastLowBattery\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"lastPowerCut\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"time\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String imei;
  @Deprecated public java.lang.String lastBatteryValue;
  @Deprecated public long lastLowBattery;
  @Deprecated public long lastPowerCut;
  @Deprecated public long time;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeviceConnectionState() {}

  /**
   * All-args constructor.
   * @param imei The new value for imei
   * @param lastBatteryValue The new value for lastBatteryValue
   * @param lastLowBattery The new value for lastLowBattery
   * @param lastPowerCut The new value for lastPowerCut
   * @param time The new value for time
   */
  public DeviceConnectionState(java.lang.String imei, java.lang.String lastBatteryValue, java.lang.Long lastLowBattery, java.lang.Long lastPowerCut, java.lang.Long time) {
    this.imei = imei;
    this.lastBatteryValue = lastBatteryValue;
    this.lastLowBattery = lastLowBattery;
    this.lastPowerCut = lastPowerCut;
    this.time = time;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return imei;
    case 1: return lastBatteryValue;
    case 2: return lastLowBattery;
    case 3: return lastPowerCut;
    case 4: return time;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: imei = (java.lang.String)value$; break;
    case 1: lastBatteryValue = (java.lang.String)value$; break;
    case 2: lastLowBattery = (java.lang.Long)value$; break;
    case 3: lastPowerCut = (java.lang.Long)value$; break;
    case 4: time = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'imei' field.
   * @return The value of the 'imei' field.
   */
  public java.lang.String getImei() {
    return imei;
  }

  /**
   * Sets the value of the 'imei' field.
   * @param value the value to set.
   */
  public void setImei(java.lang.String value) {
    this.imei = value;
  }

  /**
   * Gets the value of the 'lastBatteryValue' field.
   * @return The value of the 'lastBatteryValue' field.
   */
  public java.lang.String getLastBatteryValue() {
    return lastBatteryValue;
  }

  /**
   * Sets the value of the 'lastBatteryValue' field.
   * @param value the value to set.
   */
  public void setLastBatteryValue(java.lang.String value) {
    this.lastBatteryValue = value;
  }

  /**
   * Gets the value of the 'lastLowBattery' field.
   * @return The value of the 'lastLowBattery' field.
   */
  public java.lang.Long getLastLowBattery() {
    return lastLowBattery;
  }

  /**
   * Sets the value of the 'lastLowBattery' field.
   * @param value the value to set.
   */
  public void setLastLowBattery(java.lang.Long value) {
    this.lastLowBattery = value;
  }

  /**
   * Gets the value of the 'lastPowerCut' field.
   * @return The value of the 'lastPowerCut' field.
   */
  public java.lang.Long getLastPowerCut() {
    return lastPowerCut;
  }

  /**
   * Sets the value of the 'lastPowerCut' field.
   * @param value the value to set.
   */
  public void setLastPowerCut(java.lang.Long value) {
    this.lastPowerCut = value;
  }

  /**
   * Gets the value of the 'time' field.
   * @return The value of the 'time' field.
   */
  public java.lang.Long getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * @param value the value to set.
   */
  public void setTime(java.lang.Long value) {
    this.time = value;
  }

  /**
   * Creates a new DeviceConnectionState RecordBuilder.
   * @return A new DeviceConnectionState RecordBuilder
   */
  public static com.fretron.Model.DeviceConnectionState.Builder newBuilder() {
    return new com.fretron.Model.DeviceConnectionState.Builder();
  }

  /**
   * Creates a new DeviceConnectionState RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeviceConnectionState RecordBuilder
   */
  public static com.fretron.Model.DeviceConnectionState.Builder newBuilder(com.fretron.Model.DeviceConnectionState.Builder other) {
    return new com.fretron.Model.DeviceConnectionState.Builder(other);
  }

  /**
   * Creates a new DeviceConnectionState RecordBuilder by copying an existing DeviceConnectionState instance.
   * @param other The existing instance to copy.
   * @return A new DeviceConnectionState RecordBuilder
   */
  public static com.fretron.Model.DeviceConnectionState.Builder newBuilder(com.fretron.Model.DeviceConnectionState other) {
    return new com.fretron.Model.DeviceConnectionState.Builder(other);
  }

  /**
   * RecordBuilder for DeviceConnectionState instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeviceConnectionState>
    implements org.apache.avro.data.RecordBuilder<DeviceConnectionState> {

    private java.lang.String imei;
    private java.lang.String lastBatteryValue;
    private long lastLowBattery;
    private long lastPowerCut;
    private long time;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fretron.Model.DeviceConnectionState.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.imei)) {
        this.imei = data().deepCopy(fields()[0].schema(), other.imei);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastBatteryValue)) {
        this.lastBatteryValue = data().deepCopy(fields()[1].schema(), other.lastBatteryValue);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastLowBattery)) {
        this.lastLowBattery = data().deepCopy(fields()[2].schema(), other.lastLowBattery);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lastPowerCut)) {
        this.lastPowerCut = data().deepCopy(fields()[3].schema(), other.lastPowerCut);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.time)) {
        this.time = data().deepCopy(fields()[4].schema(), other.time);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing DeviceConnectionState instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fretron.Model.DeviceConnectionState other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.imei)) {
        this.imei = data().deepCopy(fields()[0].schema(), other.imei);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastBatteryValue)) {
        this.lastBatteryValue = data().deepCopy(fields()[1].schema(), other.lastBatteryValue);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastLowBattery)) {
        this.lastLowBattery = data().deepCopy(fields()[2].schema(), other.lastLowBattery);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lastPowerCut)) {
        this.lastPowerCut = data().deepCopy(fields()[3].schema(), other.lastPowerCut);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.time)) {
        this.time = data().deepCopy(fields()[4].schema(), other.time);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'imei' field.
      * @return The value.
      */
    public java.lang.String getImei() {
      return imei;
    }

    /**
      * Sets the value of the 'imei' field.
      * @param value The value of 'imei'.
      * @return This builder.
      */
    public com.fretron.Model.DeviceConnectionState.Builder setImei(java.lang.String value) {
      validate(fields()[0], value);
      this.imei = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'imei' field has been set.
      * @return True if the 'imei' field has been set, false otherwise.
      */
    public boolean hasImei() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'imei' field.
      * @return This builder.
      */
    public com.fretron.Model.DeviceConnectionState.Builder clearImei() {
      imei = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastBatteryValue' field.
      * @return The value.
      */
    public java.lang.String getLastBatteryValue() {
      return lastBatteryValue;
    }

    /**
      * Sets the value of the 'lastBatteryValue' field.
      * @param value The value of 'lastBatteryValue'.
      * @return This builder.
      */
    public com.fretron.Model.DeviceConnectionState.Builder setLastBatteryValue(java.lang.String value) {
      validate(fields()[1], value);
      this.lastBatteryValue = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lastBatteryValue' field has been set.
      * @return True if the 'lastBatteryValue' field has been set, false otherwise.
      */
    public boolean hasLastBatteryValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lastBatteryValue' field.
      * @return This builder.
      */
    public com.fretron.Model.DeviceConnectionState.Builder clearLastBatteryValue() {
      lastBatteryValue = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastLowBattery' field.
      * @return The value.
      */
    public java.lang.Long getLastLowBattery() {
      return lastLowBattery;
    }

    /**
      * Sets the value of the 'lastLowBattery' field.
      * @param value The value of 'lastLowBattery'.
      * @return This builder.
      */
    public com.fretron.Model.DeviceConnectionState.Builder setLastLowBattery(long value) {
      validate(fields()[2], value);
      this.lastLowBattery = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lastLowBattery' field has been set.
      * @return True if the 'lastLowBattery' field has been set, false otherwise.
      */
    public boolean hasLastLowBattery() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lastLowBattery' field.
      * @return This builder.
      */
    public com.fretron.Model.DeviceConnectionState.Builder clearLastLowBattery() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastPowerCut' field.
      * @return The value.
      */
    public java.lang.Long getLastPowerCut() {
      return lastPowerCut;
    }

    /**
      * Sets the value of the 'lastPowerCut' field.
      * @param value The value of 'lastPowerCut'.
      * @return This builder.
      */
    public com.fretron.Model.DeviceConnectionState.Builder setLastPowerCut(long value) {
      validate(fields()[3], value);
      this.lastPowerCut = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'lastPowerCut' field has been set.
      * @return True if the 'lastPowerCut' field has been set, false otherwise.
      */
    public boolean hasLastPowerCut() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'lastPowerCut' field.
      * @return This builder.
      */
    public com.fretron.Model.DeviceConnectionState.Builder clearLastPowerCut() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'time' field.
      * @return The value.
      */
    public java.lang.Long getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * @param value The value of 'time'.
      * @return This builder.
      */
    public com.fretron.Model.DeviceConnectionState.Builder setTime(long value) {
      validate(fields()[4], value);
      this.time = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'time' field.
      * @return This builder.
      */
    public com.fretron.Model.DeviceConnectionState.Builder clearTime() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public DeviceConnectionState build() {
      try {
        DeviceConnectionState record = new DeviceConnectionState();
        record.imei = fieldSetFlags()[0] ? this.imei : (java.lang.String) defaultValue(fields()[0]);
        record.lastBatteryValue = fieldSetFlags()[1] ? this.lastBatteryValue : (java.lang.String) defaultValue(fields()[1]);
        record.lastLowBattery = fieldSetFlags()[2] ? this.lastLowBattery : (java.lang.Long) defaultValue(fields()[2]);
        record.lastPowerCut = fieldSetFlags()[3] ? this.lastPowerCut : (java.lang.Long) defaultValue(fields()[3]);
        record.time = fieldSetFlags()[4] ? this.time : (java.lang.Long) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
