/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fretron.Model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum GeofenceType {
  Proximity, Polygon  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"GeofenceType\",\"namespace\":\"com.fretron.Model\",\"symbols\":[\"Proximity\",\"Polygon\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
