/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fretron.Model;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PaymentCondition extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4176448315099622298L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentCondition\",\"namespace\":\"com.fretron.Model\",\"fields\":[{\"name\":\"duration\",\"type\":[\"null\",\"long\"],\"default\":null,\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Long duration;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaymentCondition() {}

  /**
   * All-args constructor.
   * @param duration The new value for duration
   */
  public PaymentCondition(java.lang.Long duration) {
    this.duration = duration;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return duration;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: duration = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'duration' field.
   * @return The value of the 'duration' field.
   */
  public java.lang.Long getDuration() {
    return duration;
  }

  /**
   * Sets the value of the 'duration' field.
   * @param value the value to set.
   */
  public void setDuration(java.lang.Long value) {
    this.duration = value;
  }

  /**
   * Creates a new PaymentCondition RecordBuilder.
   * @return A new PaymentCondition RecordBuilder
   */
  public static com.fretron.Model.PaymentCondition.Builder newBuilder() {
    return new com.fretron.Model.PaymentCondition.Builder();
  }

  /**
   * Creates a new PaymentCondition RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaymentCondition RecordBuilder
   */
  public static com.fretron.Model.PaymentCondition.Builder newBuilder(com.fretron.Model.PaymentCondition.Builder other) {
    return new com.fretron.Model.PaymentCondition.Builder(other);
  }

  /**
   * Creates a new PaymentCondition RecordBuilder by copying an existing PaymentCondition instance.
   * @param other The existing instance to copy.
   * @return A new PaymentCondition RecordBuilder
   */
  public static com.fretron.Model.PaymentCondition.Builder newBuilder(com.fretron.Model.PaymentCondition other) {
    return new com.fretron.Model.PaymentCondition.Builder(other);
  }

  /**
   * RecordBuilder for PaymentCondition instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentCondition>
    implements org.apache.avro.data.RecordBuilder<PaymentCondition> {

    private java.lang.Long duration;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fretron.Model.PaymentCondition.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.duration)) {
        this.duration = data().deepCopy(fields()[0].schema(), other.duration);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentCondition instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fretron.Model.PaymentCondition other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.duration)) {
        this.duration = data().deepCopy(fields()[0].schema(), other.duration);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'duration' field.
      * @return The value.
      */
    public java.lang.Long getDuration() {
      return duration;
    }

    /**
      * Sets the value of the 'duration' field.
      * @param value The value of 'duration'.
      * @return This builder.
      */
    public com.fretron.Model.PaymentCondition.Builder setDuration(java.lang.Long value) {
      validate(fields()[0], value);
      this.duration = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'duration' field has been set.
      * @return True if the 'duration' field has been set, false otherwise.
      */
    public boolean hasDuration() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'duration' field.
      * @return This builder.
      */
    public com.fretron.Model.PaymentCondition.Builder clearDuration() {
      duration = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public PaymentCondition build() {
      try {
        PaymentCondition record = new PaymentCondition();
        record.duration = fieldSetFlags()[0] ? this.duration : (java.lang.Long) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
